package com.vieboo.vbankapp;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vieboo.vbankapp.data.PersonImageBean;
import com.vieboo.vbankapp.data.UserInfo;

import com.vieboo.vbankapp.PersonImageBeanDao;
import com.vieboo.vbankapp.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personImageBeanDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final PersonImageBeanDao personImageBeanDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personImageBeanDaoConfig = daoConfigMap.get(PersonImageBeanDao.class).clone();
        personImageBeanDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        personImageBeanDao = new PersonImageBeanDao(personImageBeanDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(PersonImageBean.class, personImageBeanDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        personImageBeanDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public PersonImageBeanDao getPersonImageBeanDao() {
        return personImageBeanDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
