package com.vieboo.vbankapp;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.vieboo.vbankapp.data.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO".
*/
public class UserInfoDao extends AbstractDao<UserInfo, String> {

    public static final String TABLENAME = "USER_INFO";

    /**
     * Properties of entity UserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property ImageUrl = new Property(1, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Sex = new Property(3, Integer.class, "sex", false, "SEX");
        public final static Property Number = new Property(4, String.class, "number", false, "NUMBER");
        public final static Property DepartmentId = new Property(5, Integer.class, "departmentId", false, "DEPARTMENT_ID");
        public final static Property PositionId = new Property(6, Integer.class, "positionId", false, "POSITION_ID");
        public final static Property Auth = new Property(7, Integer.class, "auth", false, "AUTH");
        public final static Property Nation = new Property(8, String.class, "nation", false, "NATION");
        public final static Property Company = new Property(9, String.class, "company", false, "COMPANY");
        public final static Property Birthday = new Property(10, java.util.Date.class, "birthday", false, "BIRTHDAY");
        public final static Property Phone = new Property(11, String.class, "phone", false, "PHONE");
        public final static Property Address = new Property(12, String.class, "address", false, "ADDRESS");
        public final static Property PoliticsStatus = new Property(13, String.class, "politicsStatus", false, "POLITICS_STATUS");
        public final static Property IdCard = new Property(14, String.class, "idCard", false, "ID_CARD");
    }


    public UserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"IMAGE_URL\" TEXT," + // 1: imageUrl
                "\"NAME\" TEXT," + // 2: name
                "\"SEX\" INTEGER," + // 3: sex
                "\"NUMBER\" TEXT," + // 4: number
                "\"DEPARTMENT_ID\" INTEGER," + // 5: departmentId
                "\"POSITION_ID\" INTEGER," + // 6: positionId
                "\"AUTH\" INTEGER," + // 7: auth
                "\"NATION\" TEXT," + // 8: nation
                "\"COMPANY\" TEXT," + // 9: company
                "\"BIRTHDAY\" INTEGER," + // 10: birthday
                "\"PHONE\" TEXT," + // 11: phone
                "\"ADDRESS\" TEXT," + // 12: address
                "\"POLITICS_STATUS\" TEXT," + // 13: politicsStatus
                "\"ID_CARD\" TEXT);"); // 14: idCard
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(2, imageUrl);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Integer sex = entity.getSex();
        if (sex != null) {
            stmt.bindLong(4, sex);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(5, number);
        }
 
        Integer departmentId = entity.getDepartmentId();
        if (departmentId != null) {
            stmt.bindLong(6, departmentId);
        }
 
        Integer positionId = entity.getPositionId();
        if (positionId != null) {
            stmt.bindLong(7, positionId);
        }
 
        Integer auth = entity.getAuth();
        if (auth != null) {
            stmt.bindLong(8, auth);
        }
 
        String nation = entity.getNation();
        if (nation != null) {
            stmt.bindString(9, nation);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(10, company);
        }
 
        java.util.Date birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindLong(11, birthday.getTime());
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(12, phone);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(13, address);
        }
 
        String politicsStatus = entity.getPoliticsStatus();
        if (politicsStatus != null) {
            stmt.bindString(14, politicsStatus);
        }
 
        String idCard = entity.getIdCard();
        if (idCard != null) {
            stmt.bindString(15, idCard);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(2, imageUrl);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Integer sex = entity.getSex();
        if (sex != null) {
            stmt.bindLong(4, sex);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(5, number);
        }
 
        Integer departmentId = entity.getDepartmentId();
        if (departmentId != null) {
            stmt.bindLong(6, departmentId);
        }
 
        Integer positionId = entity.getPositionId();
        if (positionId != null) {
            stmt.bindLong(7, positionId);
        }
 
        Integer auth = entity.getAuth();
        if (auth != null) {
            stmt.bindLong(8, auth);
        }
 
        String nation = entity.getNation();
        if (nation != null) {
            stmt.bindString(9, nation);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(10, company);
        }
 
        java.util.Date birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindLong(11, birthday.getTime());
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(12, phone);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(13, address);
        }
 
        String politicsStatus = entity.getPoliticsStatus();
        if (politicsStatus != null) {
            stmt.bindString(14, politicsStatus);
        }
 
        String idCard = entity.getIdCard();
        if (idCard != null) {
            stmt.bindString(15, idCard);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public UserInfo readEntity(Cursor cursor, int offset) {
        UserInfo entity = new UserInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // imageUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // sex
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // number
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // departmentId
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // positionId
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // auth
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // nation
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // company
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // birthday
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // phone
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // address
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // politicsStatus
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14) // idCard
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setImageUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSex(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setNumber(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDepartmentId(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setPositionId(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setAuth(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setNation(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCompany(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBirthday(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setPhone(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAddress(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setPoliticsStatus(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setIdCard(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
     }
    
    @Override
    protected final String updateKeyAfterInsert(UserInfo entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(UserInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
